### ISSUE TITLE
Anyway to reput on DRM?

### ISSUE THREAD

**Issue by batrachophagous1** [Magisk-Modules-Repo/magisk-drm-disabler#2]
I can't watch Disney now didn't read the mod description. Is there any way to put DRM back?

**Comment by Atrate** [comment]
If it does not "come back" after removing the module, you'll need to factory reset your phone.

**Comment by IsHacker003** [comment]
> I can't watch Disney now didn't read the mod description. Is there any way to put DRM back?

Cancel your subscription and uninstall that app. DRM is an injustice to people.
